CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE attendance (
  id SERIAL PRIMARY KEY,
  user_id INT REFERENCES users(id),
  time TIMESTAMP DEFAULT NOW()
);